### ISSUE TITLE
Move Closer to Palmers Road to Reduce Commute

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#11]
@iteles a while back we discussed the idea of moving _closer_ to **Palmers' Road** so we would not have to commute **35mins _each way_** from MDC. 

Well, today I spotted that `#13 Palmers Road` is available for rent and called them up.
![13-palmers-road-london-flat-for-rent](https://cloud.githubusercontent.com/assets/194400/19436642/462f720a-9469-11e6-800f-4f17843d386e.png)
## Cost
- Rent: 2,250 pcm
- Council Tax: 150
- Energy: 200
- Broadband: We can range-extend from FAC so no extra cost here. 

Working total cost: £2,600 

> Note: I have requested additional costs estimates from the estate agent.
## Rental
- room 1: £850 (us, the lead Tennent)
- room 2: £850 (_our awesome flatmates_) http://www.spareroom.co.uk/flatshare/?search_id=390677671
- room 3: AirBnB £900 (_the Campbells make £1,300 but are closer to the center_)

Total income: £2,600 (_predicted_) 

If we _estimate_ that we currently "spend" **10 days** per month at FAC it's 20 hours of commute time.
If we _conservatively_ charge £20 per hour to clients we will save £400 per month.
(_as you know our rates are a little higher so our corresponding saving would be more._)

The main selling point for me is that I could work from the `#QuietSpace` more often and for longer, walk across the street and go straight to sleep. `#DieEmptyEveryDay` 

We are about to go into "Startup Mode" we need to _eliminate_ any time-wasting activities (commuting) and focus!

_Expected_ total **time** for the move: 1 weekend. (We would only clear out our room and the upstairs closet and bring anything else we want from the office)

Plus the time to find someone to take over our room at MDC. (`M` can help...)

## Todo/Tasks

+ [x] Contact estate agent(s)
+ [x] Organise viewing(s)
+ [x] Make offer
+ [x] Sign contract
+ [x] Provide passports
+ [x] Provide references
+ [x] Transfer deposit
+ [x] Pick up keys
+ [x] Transfer first month's rent
+ [x] Pack
+ [x] Paint/fix wall of office at *old* house
+ [x] Move
+ [x] Get hyperoptic into Palmers Road
+ [x] Take photos of whole new flat
+ [x] Take water and electricity meter readings
+ [x] Switch over electricity and water to our name 
+ [x] Buy vacuum cleaner
+ [x] Book deep clean of Palmers Road
+ [x] Take stock of cleaning products and buy new ones required
+ [x] Unpack and put everything away
+ [x] Make Ikea shopping list
+ [x] Ikea trip!

**Comment by jackcarlisle** [comment]
@nelsonic just as a note for AirBnB, you need to make sure that there is no prohibition to subletting in the tenancy agreement

**Comment by nelsonic** [comment]
@jackcarlisle do the places you are _currently_ looking at allow subletting (_contractually_)?

**Comment by jackcarlisle** [comment]
@nelsonic some do and some don't. Sometimes all the landlord cares about is getting their rent each month and they don't mind if it's through subletting

**Comment by nelsonic** [comment]
Got this reply from the letting agent:
![13-palmers-road-flat-costs](https://cloud.githubusercontent.com/assets/194400/19440996/ea1a5332-947b-11e6-8f17-348188f3176f.png)
man it's expensive just to _rent_ a place in London...! 😕 

Asked for viewing this afternoon/evening. let's see if they get back to us.

**Comment by iteles** [comment]
I'm working on numbers but ultimately, at this stage and for this next year, saving ourselves the commute is not only worth it, but necessary. 

We should go for a 12 month contract with a 6 month break clause or a 6 month contract.

**Comment by iteles** [comment]
3 bedroom places are proving very hard to find in the area.

2 bedroom places are more realistic but tend to be in the region of £1,800 *without* bills. Ouch. Having a mortgage is a lot cheaper than renting in London...!

**Comment by nelsonic** [comment]
@iteles I think a 2-bed place is the way to go at this point. 
My understanding is @jackcarlisle will stay at his current spot in West London for foreseeable future. ✅ 
As much as it _pains_ me to spend (_waste_) money on Rent (when we could _easily_ buy with a minimal deposit and some proof of earnings, see: https://www.freelancerfinancials.uk.com/mortgages-for-contractors/ ) we do need to think about moving soon... commuting is lame.

**Comment by jackcarlisle** [comment]
@nelsonic yeah hopefully staying central until March and then making the move West

**Comment by nelsonic** [comment]
We've now viewed 4 flats _on_ or _near_ Palmers Road. 🔍 
We have one more viewing booked for Tuesday. 📆 
`.then` we need to _decide_ and then make our move. 📦 🚀 

> @jackcarlisle feel free to `unsubscribe` from the issue if it's "noisy"... 🙉 😉

**Comment by nelsonic** [comment]
@iteles What `else` do we _still_ need to do for the move...?
(_please update the checklist in the first comment of the issue..._) 😉

**Comment by iteles** [comment]
Updated! We've gone for a small flat on Palmers' Road.

**Comment by iteles** [comment]
Updated checklist in the top comment :arrow_up:

**Comment by nelsonic** [comment]
The tasks/checklist is _almost_ done ... 
@iteles, please let me know if/how I can help with the last few items ... 👍

**Comment by nelsonic** [comment]
done. saved @iteles  a few hundred hours. 👍
