### ISSUE TITLE
What is the law on non-permanent structures on agricultural land in Portugal?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#114]
Yesterday when we went to visit the potential "MVP" land https://github.com/dwyl/phase-two/issues/25#issuecomment-1221627814 I asked the the estate agent (Eugenio) about having a non-permanent structure on the land. He said that it depends on a number of factors ... in general the short answer is "No" you can't have a non-permanent structure as it would be classed as "camping" and they would require you to move/remove it. 

So we need to investigate & understand the law on this ASAP. 

# Todo

+ [x] Email [`team@pureportugal.co.uk`](mailto:team@pureportugal.co.uk) to ask if they can share the legislation with us.
+ [x] Do our own independent desk research
+ [x] Write-up the conclusions

**Comment by Stephanymtr** [comment]
Alright, so I looked through all the comments on Land MVP and most of the issues on "phase-two", and here is what I understand so far. You guys are:
- buying a piece of land 
- planting a LOT of trees on this land
- setting up modern self-contained container homes for travelers to stay

1- You want to set up a self-sufficient off-the-grid temporary stay business... ??
2 - I take the container home idea is the non-permanent structure you are talking about here... ?? 
3 - So you want me to investigate & understand the law on what you would need to be legally able to set this all up - before buying the actual land... is all of this correct ?

**Comment by nelsonic** [comment]
@Stephanymtr thanks for reading through the thoughts in this repo and making sense of it. 👌 
Yes, the non-permanent structure would be a shipping container. 
Initially it would be for storage and then it would be transformed into a container home. 

As per the OP/description, the first sept is to send a contact request to PurePortugal: https://www.pureportugal.co.uk/contact/

I've signed up to the "Pure Portugal Plus" at £18/year:
https://www.pureportugal.co.uk/pure-portugal-plus/
<img width="612" alt="image" src="https://user-images.githubusercontent.com/194400/186597531-a139b5b8-a4f8-4dbc-a1c1-ee63552eabc4.png">

Sent the following contact request:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/194400/186605483-29186178-95d4-4471-accb-ceda36e3c51a.png">


```
Hi! We'd like to buy land in Portugal with a view to placing a non-permanent structure on it 
e.g. Tiny home on wheels or shipping container home. Is this legal? What are the restrictions?
You appear to be the experts, so if you can point us in the right direction 
it would be much appreciated. 
Signed up to the "PURE PORTUGAL PLUS" direct debit 
and very happy to pay hourly for consulting to save time/hassle. 
Thanks in advance & kind regards,
Nelson
```

<img width="463" alt="image" src="https://user-images.githubusercontent.com/194400/186605803-cb487a00-da12-409d-a1e9-5d1d5e4a72fb.png">

Got a confirmation that they received it:
<img width="663" alt="image" src="https://user-images.githubusercontent.com/194400/186605950-a83b01e7-8c28-4842-a02f-b78f9c5a6119.png">


Now we need to do our own research to understand the legislation. 🔍  **`#HelpWanted`** 🙏 

> **Note**: To be clear on the priority of this issue: it's **`priority-1`** for _me_ (Nelson)
because I would like to buy a _small_ piece of land with either it's own spring or year-round river access. 
> The idea, as you note and briefly outlined in https://github.com/dwyl/phase-two/issues/25 is to buy land, setup irrigation using the "_free_" water and then plant _lots_ of trees. If we can place a non-perm structure on it then we could visit once a month to tend to the trees and get away from the city. 💭

**Comment by Stephanymtr** [comment]
Alright, I will get started on that research 👍

**Comment by Stephanymtr** [comment]
I know this issue is strictly for us to learn about the legislation on non-permanent structures @nelsonic , but  construcao e habitacao de residencia propria is also something I should look into as well ? I mean, you will be using the container as storage temporarily, but I take you will be building a home/homes at some point as well.

**Comment by Stephanymtr** [comment]
### - just taking a lunch break, research not done yet. 

----------------------------

PDR2020: Instalações de Alojamento Temporário Amovíveis – Investimento na Exploração Agrícola
https://www.agroportal.pt/wp-content/uploads/2021/08/OTE_145_321_IATA.pdf
https://www.agroportal.pt/wp-content/uploads/2021/08/Aviso26da321_IATA.pdf
http://www.pdr-2020.pt/O-PDR2020/Arquitetura/Area-2-Competitividade-e-Organizacao-da-Producao/Medida-3-Valorizacao-da-Producao-Agricola/Acao-3.2-Investimento-na-Exploracao-Agricola/Operacao-3.2.1-Investimento-na-Exploracao-Agricola

Have you guys heard of PDR 2020? 
_O PDR 2020 é o instrumento financeiro, que através do FEADER, apoia o setor agroflorestal e o desenvolvimento rural no Continente, complementando os restantes instrumentos da política agrícola comum (PAC), da política de coesão e da política comum de pescas, enquadrados no Portugal 2020._

You guys should keep an eye on their agenda. I found out they were encouraging Investimento na Exploração Agrícola last year. The incentive was destinado a “Instalações de Alojamento Temporário Amovíveis” nos concelhos de Odemira e Aljezur. 

<img width="864" alt="Screenshot 2022-08-25 at 11 17 31" src="https://user-images.githubusercontent.com/91985721/186639501-8657097c-06d2-4541-a9db-fd8258868497.png">

It doesn't hurt to keep an eye on their upcoming anuncios of incentives. 

-------------------------
Am I right to assuming the land you guys are interested in buying may belong to RAN ?
Here is the legislação regarding Reserva Agrícola Nacional:

[Decreto-Lei nº 199/2015](https://dre.pt/application/conteudo/70309902), de 16 de setembro
Procede à primeira alteração ao Decreto-Lei n.º 73/2009, de 31 de março, que aprova o regime jurídico da Reserva Agrícola Nacional

[Decreto-Lei nº 73/2009](http://dre.pt/pdf1sdip/2009/03/06300/0198802000.pdf), de 31 março
Aprova o regime jurídico da Reserva Agrícola Nacional e revoga o [Decreto-Lei n.º 196/89](http://dre.pt/pdf1sdip/1989/06/13400/23182327.pdf), de 14 de junho.

[Portaria nº 162/2011, de 18 abril](http://dre.pt/pdf1sdip/2011/04/07600/0232702332.pdf)
Define os limites e condições para a viabilização das utilizações não agrícolas de áreas integradas na Reserva Agrícola Nacional.

[Portaria nº 1403/02](http://dre.pt/pdf1sdip/2002/10/250B00/69856986.pdf), de 29 de outubro
Procede a ajustamentos nos valores e nos critérios relativos ao cálculo das taxas a cobrar pelos serviços prestados pelo Centro Nacional de Reconhecimento e Ordenamento Agrário. Revoga a [Portaria n.º 389/90](http://dre.pt/pdf1sdip/1990/05/11800/23322333.pdf), de 23 de maio.

[Declaração de Retificação nº 15/2011](http://dre.pt/pdf1sdip/2011/05/09900/0288602886.pdf), de 23 de maio
Retifica a [Portaria n.º 162/2011](http://dre.pt/pdf1sdip/2011/04/07600/0232702332.pdf), de 18 de abril, dos Ministérios da Economia, da Inovação e do Desenvolvimento, da Agricultura, do Desenvolvimento Rural e das Pescas, das Obras Públicas, Transportes e Comunicações e do Ambiente e do Ordenamento do Território, que define os limites e condições para a viabilização das utilizações não agrícolas de áreas integradas na Reserva Agrícola Nacional.

https://dre.pt/dre/legislacao-consolidada/decreto-lei/2009-34546775

**It's huge**. There are loads of important points that will interest you e.g., 

Legislation sobre Utilização de áreas da RAN para outros fins https://dre.pt/dre/legislacao-consolidada/decreto-lei/2009-34546775-73187087?_ts=1656720000034

<img width="1118" alt="Screenshot 2022-08-25 at 09 46 15" src="https://user-images.githubusercontent.com/91985721/186619300-3fc88763-9801-43e0-92d8-76a755a8ba24.png"> 
-
Although there is general legislation (links above), each town council can set their own set of rules what is allowed in certain areas. This means that when the land you are looking into is part of the National Agriculture Reserved, you will need their approval AS WELL AS the Camara Municipal approval. Do you already have an idea of the towns you want buy land ? If yes, I'd suggest digging deeper by contacting their camaras separately... maybe even scheduling a meeting (consulta) with the gabinete de projectos ?! 

---------------------------

The [Entidade Regional da Reserva Agrícola do Norte](https://www.dgadr.gov.pt/reserva-agricola-nacional-ran#:~:text=Aprova%20o%20regime%20jur%C3%ADdico%20da%20Reserva%20Agr%C3%ADcola%20Nacional%20e%20revoga,89%2C%20de%2014%20de%20junho.&text=Define%20os%20limites%20e%20condi%C3%A7%C3%B5es,integradas%20na%20Reserva%20Agr%C3%ADcola%20Nacional.) is in Braga 🍾 
<img width="574" alt="Screenshot 2022-08-25 at 10 29 47" src="https://user-images.githubusercontent.com/91985721/186629278-6c245e9a-4fb7-4e56-bc2a-49b2fc7eb532.png">

Mail: erran@drapnorte.gov.pt
http://ran.drapnorte.gov.pt/

-
If you go on their website & scroll down, you will see the search box. I typed in estruturas amoviveis in different ways and unfortunately nothing popped up.

<img width="1168" alt="Screenshot 2022-08-25 at 10 45 40" src="https://user-images.githubusercontent.com/91985721/186632845-ab335e58-a5d6-4c68-963b-70a298c111bc.png">
http://ran.drapnorte.gov.pt/documentos/Req_alinea_G.pdf

<img width="1161" alt="Screenshot 2022-08-25 at 10 46 35" src="https://user-images.githubusercontent.com/91985721/186633007-924ff4ab-1a91-4522-935a-af03e21c1c78.png">

----------------

 A utilização turística de áreas integradas na Reserva Agrícola Nacional (RAN): 

<img width="773" alt="Screenshot 2022-08-25 at 09 54 08" src="https://user-images.githubusercontent.com/91985721/186621080-4a9c0bfa-2993-47f0-8c3a-c2319e0e878b.png">

http://business.turismodeportugal.pt/pt/Planear_Iniciar/Ordenamento_Turistico/Reserva_Agricola_Nacional/Paginas/default.aspx

--------------------------------
https://www.realestate-algarve.info/posts/building-on-agriculture-land-1/
Good read, agricultural vs agritourism. 

-This forum is pretty recent, so good read as well
https://forumdacasa.com/discussion/73776/construir-na-reserva-agricola-nacional/

-This ones is not as recent but touches up on the "temporary" non-permanent structure placed on the property, not the same situation as yours.
https://forumdacasa.com/discussion/44343/licenciamento-estrutura-amovivel/

**Comment by nelsonic** [comment]
> "_you will be using the container as storage temporarily, but I take you will be building a home/homes at some point as well._"

For now I just want to know if it's legal to place a shipping container on a piece of rustic/farm land. 📦 
If we can get a _cheap_ piece of land it will allow us to experiment and plant some trees #6 🌳 
If we aren't able to convert it to a container home that's fine; we can just camp there once a month. ⛺

**Comment by nelsonic** [comment]
Reading: 
+ https://www.pureportugal.co.uk/blogs/tiny-homes-permission-the-lowdown/ 
+ https://www.pureportugal.co.uk/blogs/tiny-homes-permission-the-lowdown-part-2/

⏳

**Comment by Stephanymtr** [comment]
This is very good content created by Raphael from Pure Portugal. He is mostly talking about tiny homes. Good read.

<img width="868" alt="Screenshot 2022-08-25 at 13 08 44" src="https://user-images.githubusercontent.com/91985721/186660392-0861d381-db7c-4132-a0d1-d5d07e64eebf.png">

https://portugalpropertyscout.com/tiny-homes-permission-rules-laws-and-regulations/
https://www.pureportugal.co.uk/blogs/tiny-homes-permission-the-lowdown/ (comments are good to skim through as well)*

_If you put a house on wheels or use a mobile home, it might be considered «wild camping» and town hall _might_ require you to remove it. Even if it truly serves as temporary housing, the law says temporary cannot go beyond 365 days. And to qualify as temporary, the house cannot have foundations or be connected to public utilities such has electricity, water and sewage. Because, taxes._

<img width="931" alt="Screenshot 2022-08-25 at 13 03 43" src="https://user-images.githubusercontent.com/91985721/186659476-8aa798e6-42c8-4598-8f1e-45aa9100a100.png">

It goes back to what I already mentioned above regarding contacting the Camara Municipal directly.

<img width="904" alt="Screenshot 2022-08-25 at 13 20 57" src="https://user-images.githubusercontent.com/91985721/186663145-c2f73e08-bb7b-410a-8670-3f2358e04808.png">
<img width="904" alt="Screenshot 2022-08-25 at 13 22 11" src="https://user-images.githubusercontent.com/91985721/186663159-32725842-7843-4e91-981d-dcc480e63d4f.png">

* comment on PP
<img width="746" alt="Screenshot 2022-08-25 at 13 32 22" src="https://user-images.githubusercontent.com/91985721/186665613-c34cb8fc-66a3-4a64-8705-ed4b26c2d4d6.png">

https://www.youtube.com/c/PurePortugal/videos

https://www.youtube.com/watch?v=yG6dSiQcFj4

https://www.facebook.com/groups/pureportugalgoodlife/discussion/preview

----

If you are willing to pay to chat with someone knowledgeable in the area, you could MAYBE also contact an arquitecto e.g. https://www.lookalgarve-arquitectos.com/alojamentos-temporarios

It might also be worth contacting a lawyer at some point e.g. https://www.pureportugal.co.uk/directory/lawyer/

**Comment by Stephanymtr** [comment]
I called a few companies that sell containers to ask if they know anything about placing container on a piece of land in PT and most of them said : "a princípio não há problema, mas o correto é contactar a câmara para que não impliquem consigo" 

https://socontentores.pt/
https://www.hmaj-containers.com/

**Comment by Stephanymtr** [comment]
@nelsonic I contacted The [Entidade Regional da Reserva Agrícola do Norte](https://www.dgadr.gov.pt/reserva-agricola-nacional-ran#:~:text=Aprova%20o%20regime%20jur%C3%ADdico%20da%20Reserva%20Agr%C3%ADcola%20Nacional%20e%20revoga,89%2C%20de%2014%20de%20junho.&text=Define%20os%20limites%20e%20condi%C3%A7%C3%B5es,integradas%20na%20Reserva%20Agr%C3%ADcola%20Nacional.) just now over the phone  https://github.com/dwyl/phase-two/issues/114#issuecomment-1227069738

I spoke with Cristina Fernandes who said you do need uma autorizacao before placing a storage container on your property. She was nice, but didn't talk much. She said to pass by the entidade in person before buying the container/land, she will explain the restrictions and give you all the paperwork necessary for application. Success! 💯  This entidade cover the entire north of the country (from Aveiro upwards). This doesn't mean you wouldn't still have to contact Camara Municipal and other entidades, but it seems like this might be a good first stop. 

![image](https://user-images.githubusercontent.com/91985721/186687120-4b3cd0ab-d6d2-4348-a56c-4a8e15e4e58b.png)

**Comment by nelsonic** [comment]
Solid research @Stephanymtr 👌 thanks for proactively calling the Câmara Municipal and speaking with Cristina. 💡 
It seems like the conclusion is: any house tiny/off-grid or not is classed as "habitation" so **must be licensed**. 🙄 
Obviously if the land was big/remote enough and there were established trees to cover the container from Google Earth ... the container could be placed (and transformed) without anyone bothering us. 💭 

I think our best bet is going to be to just buy land with a ruin on it that we can rebuild. e.g: https://github.com/dwyl/phase-two/issues/25#issuecomment-1227697747

**Comment by nelsonic** [comment]
The conclusion is: don't waste our time on land without a ruin on it (that we can rebuild).
By having a ruin, we can place a container on it as a "reconstruction support" building.

**Comment by iteles** [comment]
Some excellent contacts in here as well which we shouldn't lose. 
Learnt a lot from reading through this. Thanks!

**Comment by iteles** [comment]
On this and linked to #116, I just wanted to drop this link here which talks a little about the bureaucracy of tiny houses specifically: https://youtu.be/rLKLiyQSWfk?t=514

We should open a separate issue on tiny houses but also talks about `estruturas amovíveis`.

**Comment by nelsonic** [comment]
Inês did you mean to share that 25 minute intro video that could have been a 1 minute? 🤷🏼‍♂️

**Comment by nelsonic** [comment]
They are building a tiny house on a trailer. Nothing new. But a load capacity of 2700kg is *nothing*. They would need at *least* double this to make something decent. 

![2CC2BDD5-5CD6-450A-83FA-38FFBF200E60](https://user-images.githubusercontent.com/194400/188013199-0df45adf-5b0f-425c-b309-2682e1d72d8e.jpeg)

This is what they should have used:

https://m.olx.pt/d/anuncio/atrelado-martz-gt-plateau-500s-3-5t-novo-IDGEOy0.html
![EE9F3015-E9A9-4AE9-B29F-0B68A3ACB9DC](https://user-images.githubusercontent.com/194400/188013853-d3354841-b084-42c2-95a8-36785dadf172.jpeg)

**Comment by iteles** [comment]
I meant to share the one minute from the timeframe that I shared it which talks about the regulamento that they circumvented so that it didn't get lost when I closed my tabs.

**Comment by nelsonic** [comment]
Recently published/updated [06 July 2022]: 
https://www.imovirtual.com/en/noticias/lifestyle/tiny-house-portugal-legislacao-como-comprar
<img width="983" alt="image" src="https://user-images.githubusercontent.com/194400/188397728-20939cdb-4643-4b3e-bcd4-ca3691495057.png">

PDF snapshot: [Tiny-House-em-Portugal_Legislacao-e-como-comprar_Imovirtual.pdf](https://github.com/dwyl/phase-three/files/9487847/Tiny-House-em-Portugal_Legislacao-e-como-comprar_Imovirtual.pdf)
