### ISSUE TITLE
Proposal for discussion: Two-for-one dwyl architects

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#12]
# Tasks:
- [x] discuss idea with S
- [x] send proposal to P & K
- [x] follow up requesting confirmation
- [x] debrief S
- [x] start!

<hr />

Dear P & K, 

Last year when P suggested that I return to TC for the Inspirational Search project,
I accepted on the condition that I was able to bring two of DWYL's developers to be part of the team at, what I'm sure you will agree, was a competitive rate for developers with React experience.

We are very grateful that you gave Nikhi and Jack a chance to help deliver the iSearch project for the Nordics; They were both sad to leave TC when Rasmus decided to "fold-in" the project.

In the interest of both Saving TC money and bringing in fresh people I would like to make 
a proposal.

We have an exceptionally talented/driven and fast-learning young guy who has UX/Product experience, a natural talent for being a bridge between business and technical stakeholders and is a Full-Stack JavaScript & React developer .

I would like to bring him in at no extra cost to TC and have him shadow me and work with us on the Federated Search project as an "Architect Apprentice". He will be able to add value from the very first week. 

DWYL will pay him directly out of the money that TC is already paying us so there will be no budget implication.

He has great communication skills and will help improve remote-working best practice in the Federated Search team.

One of the things that all TC code projects lack is good documentation and communication, this would be his first task with my help.

Would you be interested in discussing this further?

Kind regards,

Nelson

**Comment by nelsonic** [comment]
Done.
