### ISSUE TITLE
Scouts / Girlguides Base ?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#20]
Scout/Guides 

I have a _really_ good impression of the Scout/Guide movement. https://en.wikipedia.org/wiki/Scouting
The movement embodies _many_ of the principals/ethics that make society better and I haven't _met_ a person who was a Scout/Guide I did not _like_.

One of the few things I _regret_ about my youth is _not_ having spent _more_ time in Scouts.
I went a _few_ times because my sister's BFF (_Theresa_) was an _avid_ scout, but then _chose_ to spend my time `skating` instead ... if only the Scouts had a skatepark...! 

I know @iteles attended Girlguides for a while and _really_ enjoyed it. (_please share detail!_)

> People who were in the scouts or guides in childhood have better mental health in later life, a study suggests: http://www.bbc.com/news/uk-scotland-37923133

> Interesting fact: **7.2%** of the population of Indonesia attend Scouts/Guides! see: https://en.wikipedia.org/wiki/Scouting#Membership

So, I think we need to _investigate_ getting in _contact_ with the Scout/GIrlguide Movement and seeing what the requirements would be to become an "_Official Venue_". 
We could have a Container (_or several_) on the property that was dedicated to them and different Scout/Guide groups could visit each weekend/holidays of the year to camp, explore and have a great time.

## Todo/Tasks `#help-wanted`

+ [ ] Gather as much information as possible about the scout/guide movement from people we _already_ know (_so we can ask informed questions when we contact the Orgs_)
+ [ ] Research if there are any _negative_ aspects of the movement.
+ [ ] Contact the Scout "HQ" to find out what they _require_ in a partner Org/Venue:
  + UK Contact: http://scouts.org.uk/contact-us/
  + PT Contact: http://www.escoteiros.pt/form-Contactos-1-12
+ [ ] Gather the requirements and paste as a comment in this issue so we can track them.
