### ISSUE TITLE
Moving Boxes?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#34]
@iteles `given` that we are trying to organise our move for #11 
We have a _decision_ to make regarding _how_ we transport our "_stuff_" ...
1. Go hunting for boxes at the local supermarket (_the way we have done in the past ... money-efficient potentially time-wasteful.._)
2. Buy "_cheap_" cardboard flat-pack boxes which are more uniform and thus "_tidier_" (_and save us time of having to hunt for clean boxes..._) e.g: https://www.amazon.co.uk/gp/product/B000NMDM5A/
3. Buy _plastic_ (_durable_) storage boxes from B&Q 

> _If we decide to `Buy` durable, re-useable, waterproof & pest-resistant  `plastic` boxes I can go pick them up at lunch with a `ZipCar` so we can still get lots of packing done this evening **`And`** we can use them for the [`next`](#3) move "aswell" ..._

B&Q has a few options: http://www.diy.com/search?Ntt=Storage+Box
Whereas ASDA (Walmart) only has _one_ option: https://groceries.asda.com/product/storage-tubs/george-home-white-storage-box-lid/910000045047 

## Tasks/Todo

+ [x] _**Estimate**_ how much "_stuff_" we want to:
  + [x] give to charity (_clothes and anything `else` other people can put to better use_)
  + [x] recycle (_any paper or "stuff" boxes we no longer need in the Attic_)
  + [x] store in G8 (_temporarily because we don't `need` it in #11 ..._)
  + [x] take with us to `#NewFlat` because we _need_ it.
+ [x] _**Calculate**_ how many boxes we want/need to buy for:
  + [x] storage in G8 (_durable `plastic` boxes are better for this because they are pest-resistant..._)
  + [x] transport & unpack immediately (_thus `plastic` boxes are over-kill..._)
+ [x] _**Buy**_ them ASAP so we can crack on with packing!

> How many IKEA Blue bags do we still have? (_I like using them for transporting clothes..._)

## Snapshots for reference:

![amazon-storage-box](https://cloud.githubusercontent.com/assets/194400/20339946/f2da1f80-abd6-11e6-9e1f-7cb0960031c8.png)

![diy-storage-box](https://cloud.githubusercontent.com/assets/194400/20339951/f9027d94-abd6-11e6-933a-8e741642d2a2.png)

![asda-storage-box](https://cloud.githubusercontent.com/assets/194400/20339956/fc7f8c46-abd6-11e6-9a56-3cd0aa7da747.png)

**Comment by iteles** [comment]
Wow. This is super organised. 

Whilst I'm inclined to go down the durable boxes route, we have about 5 of them in the attic already that we can use. My main issue is that we don't have anywhere to Store them at the new place. 

Your steps seem like a good starting place!

**Comment by nelsonic** [comment]
@iteles my view is that we should get _more_ less deep `plastic` (_durable/pest+weather-resistant/stackable_) boxes (_which individually store fewer things_) so they aren't as heavy to _carry_ and can be re-used for other things after our `next` move ...

**Comment by nelsonic** [comment]
@iteles keres tentar ir ao B&Q amanha de manhã para ver das caixas?

**Comment by iteles** [comment]
Sure. Time for bed then!

**Comment by nelsonic** [comment]
![img_1298](https://cloud.githubusercontent.com/assets/194400/20388593/8061cb3c-acbd-11e6-8281-544e96124e1e.JPG)
![img_1299](https://cloud.githubusercontent.com/assets/194400/20388594/8063de18-acbd-11e6-81eb-86f8a4dada11.JPG)

Bought boxes @B&Q Thisbe morning.
Ended up costing a bit more than expected
Because they hadn't sold out of the "promo" set (which I got the last one)
But I think we have enough to get the job done.

**Comment by iteles** [comment]
Thanks for sorting all of this out whilst I was at A&E :heart:

**Comment by iteles** [comment]
@nelsonic Can this be closed now? ;)

**Comment by nelsonic** [comment]
@iteles totes. done. ✅
