### ISSUE TITLE
Braga checklist

### ISSUE THREAD

**Issue by iteles** [dwyl/phase-two#56]
Things to be done for the Braga house:

+ [ ] Request vistoria from câmara (vamos fazer reabilitacao e queremos o IMT) 
  + [ ] Need to fill in a form online for vistoria antes da obra
+ [ ] Look up Artigo 45 do estatuto dos beneficios fiscais - reabilitação urbanistica, making the certificados go up 2 levels (vistoria tem de ser feita antes)
  + Quando acabares a obra, pedes outra vistoria a pedir isenção de IMI e payback de IMT
+ [ ] Certidão permanente (ir buscar à conservatória)
+ [ ] Caderneta predial (ir buscar à conservatória) - record of everything that has legally happened on the building, should be clean
+ [ ] Falar à camara para perguntar se se pode construir mais um andar (descobrir quem é o responsavel antes de ir, basta ligar) - o arquitecto da camara mas para a parte certa
  + Your own research into it using the Plano Director Municipal (PDM Braga), you can see the area your type of building yours is and then find out the rules based on that classification (ratio of construction to lot space, etc) - complement what you get from the arquitecto with this
+ [ ] Falar com arquitectos (definir 1o o que fazer mais ou menos mas perguntar se têm tempo e se querem fazer)
  + Mandar mensagem à Joana para falar ao Big
  + Henrique do http://paralelozero.pt/
  + Get orçamentos (ask Andy to show us what is included in his ones)
  + Guarantir que eles vão preparar o caderno de medições (this is what you give to builders for a budget) e o caderno de encargos (no contracto)
+ Não precisas de licensiamento se estas so a fazer por dentro, mas se fizermos mais um andar precisamos dum projecto de arquitectura + projecto de engenharia para pedir licensiamento (planning permission) à camara
+ [ ] Ver regras de aguas furtadas (our mansardas) e.g. piso de sotão https://s21.postimg.org/cmfu8ev0n/201007121012-fotos036.jpg
+ Probably won't need engineers unless we're building an additional floor

**Comment by nelsonic** [comment]
@iteles as discussed, these are my questions for the **architects discussion _today_**:
+ [ ] **Basement**:
  + [ ] Wheelchair accessible shower and bathroom 
    + [ ] is there enough space or do we need to "borrow" any from an adjacent room?
    + [ ] Do we need to ***widen the door*** (_given the building recommendation is **813mm** which is less than all the doors in the house..._ 😞 ) 
  + [ ] **Wheelchair Ramp** from ***kitchen-to-garden***
  + [ ] Wheelchair Ramp from Basement to Garden (_optional as the garage entrance can be used_)
+ [ ] **1<sup>st</sup> Floor**: 
  + Transforming the **bathroom** into **two W/C's** one with a sitting toilet the other with a urinal (_working regulations in PT `require` a Urinal for men see research!!_) 
+ [ ] **2<sup>nd</sup> Floor**: 
  + [ ] Transforming the Two (_large_) bathrooms on the 
+ [ ] **Garden**: Do we _need_ ***planning permission*** for the following (_in priority order_):
  + [ ] to remove the "bird house" and build something new in it's place?
  + [ ] to get **electricity and plumbing** outside? (_required for outside toilet and sauna..._)
  + [ ] to build a **water tank** (_to capture **rain water**_) 
  + [ ] to build a "_small swimming **pool**_"
  + [ ] to keep **fish** in an outdoor fish pond
+ [ ] "**Extra Mile**":
  + [ ] Extra Floor: What are the chances of the Braga Council accepting the idea?
    + [ ] Do we need to do any structural reinforcing (_how much would that cost?!_)
    + [ ] How much is it likely to cost if we assume similar exterior appearance and materials but open-plan (_i.e. the whole top floor would be a single office which we could divide using Glass later on..._)?
 
Please feel free to translate these to PT and send to the Achi in advance so they can prep answers.

**Comment by edwardcodes** [comment]
@iteles Hi Inês! If you need to translate any of this comments to PT please let me know!!

**Comment by nelsonic** [comment]
@iteles can we _close_ this issue? 🤔

**Comment by iteles** [comment]
Very much out of date sadly

**Comment by nelsonic** [comment]
For anyone reading this in the future, for more on Braga see: https://github.com/dwyl/home 😉
