### ISSUE TITLE
Pigmy Goats?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#74]
This morning while we were trying to have our "standup" call with our _remote_ team, 
someone nearby (_in the neighbourhood_) was mowing their lawn (_we think it was in the local park_),
and the **noise** was _super loud_ (_even with the double-glazing windows closed_)
It got me thinking ...

## Can Goats "Mow" The _Lawn_...? >> _Yes_!

> "_goats are **browsers not grazers**, when they **eat** [backyard] **grass**,
they **only clip the top like a good lawnmower**._"

[![image](https://user-images.githubusercontent.com/194400/46281065-88a9d380-c565-11e8-9df4-3be4a5dcc668.png)](https://youtu.be/J3fxgi7F_qI?t=1m)
https://youtu.be/J3fxgi7F_qI?t=1m

It _remains to be seen_ if they will _wreck_ the lawn 
or if the kitchen scraps will be "enough" to keep them from destroying our garden ... 🤔 

## Pros?

A short-list of the _advantages_ of keeping _tiny_ goats in the "back yard":

+ [ ] Easy to take care of (_provided there are no poisonous plants on the property_)  
+ [ ] They Don't Bite or _bark_ (_so people who are "afraid" of dogs should be "OK" with goats..._)
+ [ ] Super Cute, Friendly & Easily Handled
+ [ ] They can be _trained_! https://www.dummies.com/home-garden/hobby-farming/raising-goats/advanced-goat-training
+ [ ] They Eat (_love_) organic food scraps 
(_which there will be a lot of in a 20+ person house where a fresh pot of soup is made each day_)

[![image](https://user-images.githubusercontent.com/194400/46284255-00303080-c56f-11e8-8631-4ae422c4d68c.png)](https://youtu.be/SDKKlJJORBc)
https://youtu.be/SDKKlJJORBc

## How Much Space?

How much space do _pigmy_ goats need? (_is 200m<sup>2</sup> "enough"_)
if not, what is the _minimum_ for a couple of goats to live a _happy_ life?

> This is an "Open Question" and requires research. ❓ 
> If you are _interested_ in this topic and have time/skills ⏳ 
> to do a bit of Googling, please do/share! 🔍 

## Cons: Poop...? 💩 

This is our biggest (_potential_) "con" ... 😕 
We need to figure out how to "deal" with goat poop if we are to keep goats in the [**`home`**](https://github.com/dwyl/home) garden.

### _Other_ Cons...?

If you read YouTube comments, they are overwhelmingly positive. But you do get the occasional: 🙄 

![image](https://user-images.githubusercontent.com/194400/46281397-767c6500-c566-11e8-8bdc-b1bf6902ddd4.png)

![image](https://user-images.githubusercontent.com/194400/46284515-08d53680-c570-11e8-9e27-245ee3c15afa.png)

## What Type? >> _Nigerian Dwarf_ Goats

[![image](https://user-images.githubusercontent.com/194400/46282956-e2f96300-c56a-11e8-984c-ee4209ee9ce7.png)](https://youtu.be/KtO6JhW-n7Y)
https://youtu.be/KtO6JhW-n7Y

[![image](https://user-images.githubusercontent.com/194400/46281609-0fab7b80-c567-11e8-83e7-984b2bfb2656.png)](https://youtu.be/wvNSstp-7k8)
https://youtu.be/wvNSstp-7k8

## How _Many_? >> At _Least_ 2

Goats are _herd_ animals, we cannot have _just_ one. https://youtu.be/SDKKlJJORBc?t=2m51s

If we have **two _female_ goats** we could call them "Thelma & Louise" ... 😉 
Or we could continue with our Disney character naming convention:
https://www.momjunction.com/articles/disney-inspired-names-for-your-baby_00356077/
e.g: "Jasmine", "Lilo", "Cinderella", "Moana", "Merida"
We just need to be _careful_ not to name the Goats with popular _human_ names ... 
that would be baaaaad... 🙄  

Speaking of which, there are few _funny_ names too: 
https://www.thesprucepets.com/pet-goat-names-1236943
e.g: "Baaarbara", "Baaarack" (_as in Obama_), "Ramsy" or ["_Scape_"](https://en.wikipedia.org/wiki/Scapegoat) ...

## Availability?

Thankfully, certain areas of Portugal are still quite "rural" so pigmy (dwarf) goats are readily available:
https://www.olx.pt/animais/animais-de-quinta/cabras/q-cabra-an%C3%A3/
![image](https://user-images.githubusercontent.com/194400/46282858-8bf38e00-c56a-11e8-8ddd-6d0d60722858.png)

These are "_only_" €40 and they are "below the knee" (_i.e. they don't grow very big at all!_)
https://www.olx.pt/anuncio/cabrita-an-filha-IDBxvHA.html
![image](https://user-images.githubusercontent.com/194400/46282929-c2310d80-c56a-11e8-8b86-266e275e0f8a.png)

## _Before_ We _Consider_ Getting Goats ...

What are the key _considerations_ we need to have before we even _think_ about getting goat(s)...?

[![image](https://user-images.githubusercontent.com/194400/46284432-b5fb7f00-c56f-11e8-9070-2da3cb9ec79f.png)](https://youtu.be/ZhKIxXlMIB8)
https://youtu.be/ZhKIxXlMIB8

### The _Hardest_ Thing ...

The hardest thing is "disbudding" (i.e. "de-horning") the goats ...

[![image](https://user-images.githubusercontent.com/194400/46283265-d6c1d580-c56b-11e8-89ca-7fea36813af1.png)](https://youtu.be/TQ4U3KiRmw4)

I don't think we will do this. 
Although the _reasoning_ given in the video is convincing: it's for their own good.
And the goats seem pretty _content_ only a few minutes after the procedure ...
So I could be _persuaded_ ... especially if the goats will be around people who are `new` to (farm) animals.

> _**Please share your thoughts** on this topic as comments below! 
This is just an **idea** I would love people to **discuss**. Thanks you_!

**Comment by nelsonic** [comment]
+ https://www.betterhensandgardens.com/feeding-nigerian-dwarf-dairy-goats/
+ http://featherandscalefarm.com/asked-goat-health-questions

**Comment by nelsonic** [comment]
Don't ask me how I got here ... 😜 
(I was watching a homestead YT channel and saw someone milking goats/cows by hand and thought ... 
surely there's a _cheap_ milking apparatus they could buy to claw back the time they spend hand-milking ... 💭 )

https://pt.aliexpress.com/item/1005007376616315.html
<img width="1521" alt="Image" src="https://github.com/user-attachments/assets/0dc6bd95-0110-40ed-84e0-6c1d119eed79" />

`€120` is pretty cheap for a labour-saving device. 🥛 
One that you can attach easily and then go do other chores. 
Just ask @carolrmc who had to milk their dairy cow by hand when she was a girl... ⏳
