### ISSUE TITLE
Automatic Water Irrigation System (Small Scale)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#86]
A few weeks back we planted a few seedlings and they are growing well: 🌱 
![strawberries-2019](https://user-images.githubusercontent.com/194400/57177046-e1bd4b00-6e57-11e9-8d5a-a6411ed30533.jpg)
We have been watering the plants _manually_ each day, 🚰 
which only takes a few minutes and is a good break from screens, 📵 
but it means we cannot leave the house for a few days (_e.g: for a biz trip_) ✈️ 
as the plants will _die_ in the summer heat. ☀️😞 

What we need is an automatic irrigation system we can attach to the _existing_ water tap that will water the plants every day like clockwork. 

# _Constraints_

+ [ ] ***Must*** be purchased, installed and tested before Wednesday 8<sup>th</sup> of May 2019 
(_this means no ordering online which might only be delivered after that date..._)

# Todo

+ [ ] ***Research*** options for an Automatic Electronic water timer. 
  ***Must*** be:
  + [ ] simple to program
  + [ ] durable (_no "cheap" stuff that will break after one season!_)
  ***Ideal*** (_but not essential_)
  + [ ] Solar powered so no risk of battery failure
+ [ ] ***Measure*** how much irrigation hose we need to get from the front entrance past the cherry tomatoes, strawberries and chilies all the way to the Avocado tree! 
+ [ ] ***Buy*** from specialty DIY/Garden retailer
+ [ ] ***Install*** and **Program** the timer (_ideally by 6<sup>th</sup> of May to allow time for testing!_)
+ [ ] ***Test***!
