### ISSUE TITLE
Greenhouse Mister

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phase-two#88]
In order to maintain our steady supply of seedlings, we need our (mini) greenhouse to be watered consistently. We are currently watering the seedlings in the trays in the greenhouse _manually_ each morning, but this is not _sustainable_ ... 

# Todo

+ [ ] ***Investigate*** aeroponic watering systems for small-scale greenhouse
  + [ ] _ideally_ solar powered ... 
+ [ ] ***Purchase*** kit from reputable supplier
+ [ ] ***Install*** & Program
+ [ ] ***Test***!

Related to #86

**Comment by iteles** [comment]
Totally thought this was a brand name when I saw the title of the issue 😄

**Comment by nelsonic** [comment]
Could be ... but this is what I'm referring to: 
https://www.maximumyield.com/fogponics-a-new-spin-on-aeroponic-gardens/2/1401

**Comment by nelsonic** [comment]
Order placed for a Fogger and Solar powered pump:
https://github.com/nelsonic/learn-gardening/issues/9#issuecomment-595183846
